sudo: required 

language: generic

services: 
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t jkim00844/docker-react-app -f Dockerfile.dev .

script:
  - docker-compose -f docker-compose.yaml up
  
after_success:
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-884500270944"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_ACCESS_KEY